### ISSUE TITLE
Rust's ecosystem needs you to continue to improve, so please don't give up! 😂

### ISSUE THREAD

**Issue by sunli829** [stjepang/lux#1]

**Comment by BinChengZhao** [comment]
Because of your work, you've made it easier for more people to use rust asynchrony, and I hope you can adjust yourself.

**Comment by stjepang** [comment]
Not giving up, I just took time off this week to avoid burnout and am having fun by casually learning Go. :)

Previously I was only able to read Go code but not really write much of it. I actually like the language a lot!

**Comment by vkill** [comment]
Dodge a bullet.
